In [1]:
import numpy as np

In [2]:
arr1 = np.array([1.0, 2.0, 3.0])

In [3]:
arr1

array([1., 2., 3.])

In [4]:
list1 = [1.0, 2.0, 3.0]

In [5]:
arr1 + 1

array([2., 3., 4.])

In [6]:
arr1.dtype

dtype('float64')

In [8]:
arr2 = np.array([1.0, 2.0, 3.0], dtype=np.float32)

In [9]:
arr2.dtype

dtype('float32')

In [10]:
arr2.astype(np.float64).dtype

dtype('float64')

In [11]:
arr1 + arr2

array([2., 4., 6.])

In [12]:
2 * arr1

array([2., 4., 6.])

In [13]:
arr3 = np.zeros([10, 10, 10], dtype=np.float32)

In [14]:
arr3

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]

In [15]:
arr3.shape

(10, 10, 10)

In [16]:
arr3[0]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [17]:
arr4 = np.arange(27)

In [18]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [19]:
arr4 = arr4.reshape(3, 3, 3)

In [20]:
arr4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [21]:
arr4[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [22]:
arr4[1][0]

array([ 9, 10, 11])

In [23]:
arr4[1][1]

array([12, 13, 14])

In [24]:
arr4[1][:, 0]

array([ 9, 12, 15])

In [25]:
arr4[1][:, 1]

array([10, 13, 16])

In [26]:
arr4.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [27]:
arr5 = np.ones([3, 3, 3])

In [28]:
arr5

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [35]:
arr6 = np.linspace(0, 10, 10)

In [4]:
arr7 = np.linspace(0, 10, 100)

In [36]:
arr6.shape

(10,)

In [5]:
arr7

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [37]:
arr6

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [38]:
arr7 = np.random.randn(4, 4, 4)

In [39]:
arr7

array([[[-0.28242407, -0.79979746, -0.3721715 ,  0.46237488],
        [ 1.15589017,  1.35758034, -0.81203562,  0.02287272],
        [-0.30219266,  0.35702437,  0.65042147, -1.19687202],
        [ 1.84988442, -1.07454709,  1.20597577, -0.28034638]],

       [[ 0.19658865,  0.00511526, -0.42674708,  0.16562458],
        [ 0.50987329,  1.24278517, -0.16831375,  1.26448284],
        [-0.22070605,  0.75346073,  1.17365368,  0.53667031],
        [-0.50361449,  0.17335451, -0.39000896, -1.14090159]],

       [[-0.1778399 ,  0.04726796,  1.05842008,  0.11854861],
        [-0.7005407 ,  0.11310158,  1.3706766 ,  0.80940915],
        [-0.46995596,  1.45618496, -0.82554805,  1.02313829],
        [ 0.94084621, -2.97349466, -0.84597491,  0.81721947]],

       [[ 0.58805007,  2.11847799,  0.10868966, -0.38874082],
        [-0.76569903, -0.31915562, -1.11563015, -1.06015813],
        [-0.3362382 ,  0.33343977, -1.08758206,  0.15526799],
        [-1.38641795,  0.44750674,  0.92125064, -1.84583278]]])

In [40]:
np.random.seed(123)

In [41]:
arr8 = np.random.randint(10, size=5)

In [42]:
arr8

array([2, 2, 6, 1, 3])